name = "Motion"
uuid = "0bcdb53c-9385-4d13-8c48-99ad1bbe68c0"
version = "0.1.0"
authors = ["Andrea Pasquale <andrea.pasquale@outlook.it>"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ComponentArrays = "0.15.31"
ForwardDiff = "1"
LinearAlgebra = "1.12.0"
SciMLBase = "2"
StaticArrays = "1.9.16"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
